WSS-60 Pass destructive changes file to sf project deploy start explicitly
Archive metadata zip file and deletes.csv separately.
Archive target directory to make debugging easier.

diff --git a/.github/workflows/deploy-sfdx-project.yml b/.github/workflows/deploy-sfdx-project.yml
--- a/.github/workflows/deploy-sfdx-project.yml
+++ b/.github/workflows/deploy-sfdx-project.yml
@@ -117,33 +117,55 @@ jobs:
           done >target/deletes.csv
           echo "`wc -l <target/deletes.csv` component(s) marked for deletion"
 
+      - name: archive deletes.csv
+        uses: actions/upload-artifact@v4
+        with:
+          name: deletes.csv
+          path: target/deletes.csv
+
       - name: remove Apex classes and triggers marked as deleted from metadata
         run: |
           metadata_directory="target/${{ github.event.repository.name }}-${{ github.sha }}"
+          >target/deletes-apexClasses.txt
           echo "Removing Apex classes and triggers marked as deleted from metadata directory..."
-          awk -F, '{print "path=\""$1"\" fullName=\""$3"\""}' target/deletes.csv|while read line; do
+          awk -F, '{print "path=\""$1"\" type=\""$2"\" fullName=\""$3"\""}' target/deletes.csv|while read line; do
             eval $line
             # Remove files
             rm $path $path-meta.xml
-            # Remove from package manifest
+            # Remove component from package manifest.
+            # NOTE: This doesn't guarantee that the member is being removed (only) from the correct type section. E.g. 
+            #       if there is both an ApexClass and an AuraDefinitionBundle with the same full name and the ApexClass
+            #       was marked as deleted, this would also remove the AuraDefinitionBundle from the package manifest.
             sed -i.bak "/<members>${fullName}<\\/members>/d" ${metadata_directory}/package.xml
+          
+            # While we're looping over the components to be deleted; save just the Apex class names to a separate
+            # file. This will come in handy when determining which Apex tests there are in the project.
+            if [ "$type" == "ApexClass" ]; then
+              echo "${fullName}" >>target/deletes-apexClasses.txt
+            fi
           done
           rm -f ${metadata_directory}/package.xml.bak
           echo "`wc -l <target/deletes.csv` Apex class(es) and trigger(s) removed from metadata directory."
 
-      - name: zip metadata directory
+      - name: find unit test classes in project
         run: |
-          rm -f "${{ github.event.repository.name }}-${{ github.sha }}.zip" 
-          zip -r "${{ github.event.repository.name }}-${{ github.sha }}.zip" "${{ github.event.repository.name }}-${{ github.sha }}" >/dev/null
-        working-directory: target
+          echo "Finding unit tests in project..."
+          find force-app/test -name '*.cls' | while read test; do
+            testClass="$(basename "${test}" .cls)"
+            grep "${testClass}" target/deletes-apexClasses.txt >/dev/null || echo "${testClass}" >>target/test-classes.txt
+          done
 
-      - name: archive artifacts
+      - name: archive test-classes.txt
         uses: actions/upload-artifact@v4
         with:
-          name: artifact
-          path: |
-            target/${{ github.event.repository.name }}-${{ github.sha }}.zip
-            target/deletes.csv
+          name: test-classes.txt
+          path: target/test-classes.txt
+
+      - name: archive metadata directory
+        uses: actions/upload-artifact@v4
+        with:
+          name: "${{ github.event.repository.name }}-${{ github.sha }}.zip"
+          path: target/${{ github.event.repository.name }}-${{ github.sha }}
 
   deploy:
     needs:
@@ -169,12 +191,6 @@ jobs:
           mkdir -p $HOME/.config/sf
           echo '[ "@dxatscale/sfpowerscripts", "apex-code-coverage-transformer" ]' > $HOME/.config/sf/unsignedPluginAllowList.json
 
-      - name: download metadata ZIP file
-        uses: actions/download-artifact@v4
-        with:
-          name: artifact
-          path: target
-
       - name: write Ansible Vault password to file
         run: echo "${{ secrets.ansible-vault-password }}" >.vault-password
 
@@ -193,80 +209,88 @@ jobs:
               --username=${{ inputs.username }} \
               --set-default
 
+      - name: download metadata ZIP file
+        uses: actions/download-artifact@v4
+        with:
+          name: "${{ github.event.repository.name }}-${{ github.sha }}.zip"
+          path: "target/${{ github.event.repository.name }}"
+
+      - name: download deleted metadata CSV file
+        uses: actions/download-artifact@v4
+        with:
+          name: deletes.csv
+          path: target
+
       - name: create destructive change manifest for Apex classes/triggers marked with //DELETE
         run: |
           echo Creating destructive change manifest for Apex classes/triggers marked with //DELETE
           # Set some variables
           target_org="${{ inputs.username }}"
-          source_directory="${{ inputs.source-directory }}"
-          zipfile_absolute="$(cd "$(dirname "target/${{ github.event.repository.name }}-${{ github.sha }}.zip")"; pwd -P)/$(basename "target/${{ github.event.repository.name }}-${{ github.sha }}.zip")"
           
           # Get list of Apex classes and triggers on org
           echo - Getting list of Apex classes and triggers on org
-          >target/org-apex.txt
-          sf data query -t -o ${target_org} -q 'SELECT Name FROM ApexClass' --json|jq -r '.result.records[].Name' >>target/org-apex.txt
-          sf data query -t -o ${target_org} -q 'SELECT Name FROM ApexTrigger' --json|jq -r '.result.records[].Name' >>target/org-apex.txt
+          sf data query -t -o ${target_org} -q 'SELECT Name FROM ApexClass' --json|jq -r '.result.records[].Name' >target/org-apex-classes.txt
+          sf data query -t -o ${target_org} -q 'SELECT Name FROM ApexTrigger' --json|jq -r '.result.records[].Name' >target/org-apex-triggers.txt
 
           # Move Apex classes and triggers that still exist on org to delete/source
           echo - Filtering components that still exist on org
-          rm -rf delete/source
           >target/scheduled-for-destruction.txt
           >target/already-destroyed.txt
           >target/cannot-destroy.txt
-          awk -F, '{print "path=\""$1"\" type=\""$2"\" fullName=\""$3"\""}' target/deletes.csv|while read line; do
+          awk -F, '{print "type=\""$2"\" fullName=\""$3"\""}' target/deletes.csv|while read line; do
             eval $line
-            if grep "^${fullName}\$" target/org-apex.txt; then
-              echo "    Scheduling ${type}:${fullName} for destruction"
-              if [ "$type" == "ApexClass" ]; then
-                mkdir -p delete/source/classes
-                path=$(find ${source_directory} -name ${fullName}.cls)
-                echo ${path} >>target/scheduled-for-destruction.txt
-                mv $path $path-meta.xml delete/source/classes
-              elif [ "$type" == "ApexTrigger" ]; then
-                mkdir -p delete/source/triggers
-                path=$(find ${source_directory} -name ${fullName}.trigger) 
-                echo "$path" >>target/scheduled-for-destruction.txt
-                mv $path $path-meta.xml delete/source/triggers
+            if [ "$type" == "ApexClass" ]; then
+              if grep "^${fullName}\$" target/org-apex-classes.txt; then
+                echo "    Scheduling ${type}:${fullName} for destruction"
+                echo "${type}:${fullName}" >>target/scheduled-for-destruction.txt
               else
-                echo ${path} >>target/cannot-destroy.txt
-                echo "    WARNING: Support for deleting components of metadata type ${type} not implemented yet (${type}:${fullName})."
+                echo "${type}:${fullName}" >>target/already-destroyed.txt
+              fi
+            elif [ "$type" == "ApexTrigger" ]; then
+              if grep "^${fullName}\$" target/org-apex-triggers.txt; then
+                echo "    Scheduling ${type}:${fullName} for destruction"
+                echo "${type}:${fullName}" >>target/scheduled-for-destruction.txt
+              else
+                echo "${type}:${fullName}" >>target/already-destroyed.txt
               fi
             else
-              echo ${path} >>target/already-destroyed.txt
+              echo "${type}:${fullName}" >>target/cannot-destroy.txt
+              echo "    WARNING: Support for deleting components of metadata type ${type} not implemented yet (${type}:${fullName})."
             fi
           done
           
           scheduled_for_destruction=$(wc -l <target/scheduled-for-destruction.txt)
           already_destroyed=$(wc -l <target/already-destroyed.txt)
           cannot_destroy=$(wc -l <target/cannot-destroy.txt)
-          # Directory delete/source was only created in the previous section if at least one component is to be deleted
           echo "${scheduled_for_destruction} component(s) to be deleted from org, ${already_destroyed} already deleted (cannot delete ${cannot_destroy})."
-          if [ -d delete/source ]; then
+          if [ ${scheduled_for_destruction} -gt 0 ]; then
             echo "- Generating destructive change manifest..."
-            mkdir -p delete/package
-            sf project convert source --root-dir=delete/source --output-dir=delete/package
-            # Rename package.xml to destructiveChangesPre.xml
-            mv delete/package/package.xml delete/package/destructiveChangesPre.xml
-            # Add the destructiveChangesPre.xml to the zipfile
-            # It will be deployed later
-            echo "- Adding destructive change manifest to metadata package..."
-            zip -r "${zipfile_absolute}" -j delete/package/destructiveChangesPre.xml
-            echo "Ok! Added ${scheduled_for_destruction} destructive changes to ${zipfile_absolute}."
+            metadata_args=$(cat target/scheduled-for-destruction.txt|while read line; do echo -n "--metadata ${line} "; done)
+            sf project generate manifest ${metadata_args} --type pre --output-dir=target/${{ github.event.repository.name }}
+            echo "Ok! Added ${scheduled_for_destruction} destructive changes to target/${{ github.event.repository.name }}/destructiveChangesPre.xml."
           else
             echo "No destructive changes to add."
+            cat <<EOF >target/${{ github.event.repository.name }}/destructiveChangesPre.xml
+          <?xml version="1.0" encoding="UTF-8"?>
+          <Package xmlns="http://soap.sforce.com/2006/04/metadata" />
+          EOF
           fi
           echo
           
+      - name: download test classes file
+        uses: actions/download-artifact@v4
+        with:
+          name: test-classes.txt
+          path: target
+
       - name: deploy to org and run Apex tests
         run: |
-          echo "Finding unit tests in project..."
-          testflags=$(find ${{ inputs.source-directory }}/test -name '*.cls' | while read test; do
-            if ! grep -c '^\/\/ *DELETE$' "${test}" >/dev/null; then
-              echo -n "--tests=`basename ${test} .cls` "
-            fi
-          done)          
-          echo "Deploying to ${{ inputs.username }}..."
-          sf project deploy start --target-org="${{ inputs.username }}" --test-level=RunSpecifiedTests ${testflags}--coverage-formatters=json --results-dir=reports --metadata-dir="target/${{ github.event.repository.name }}-${{ github.sha }}.zip" --wait=180
+          timeout=180
+          testflags=$(cat target/test-classes.txt | while read testClass; do
+            echo -n "--tests=${testClass} "
+          done)
+          echo "Deploying to ${{ inputs.username }} and running unit tests... (timeout ${timeout} minutes)"
+          sf project deploy start --target-org="${{ inputs.username }}" --test-level=RunSpecifiedTests ${testflags}--coverage-formatters=json --results-dir=reports --metadata-dir="target/${{ github.event.repository.name }}" --wait=${timeout}
 
       - name: install apex-code-coverage-transformer plugin
         run: sf plugins install apex-code-coverage-transformer
@@ -336,3 +360,10 @@ jobs:
             -Dsonar.java.pmd.reportPaths=reports/pmd.xml
             -Dsonar.qualitygate.wait=${{ inputs.sonar-quality-gate == true }}
         if: inputs.sonar-url != ''
+
+      - name: archive target directory
+        uses: actions/upload-artifact@v4
+        with:
+          name: target
+          path: target
+        if: always()
